In [539]:
import matplotlib.pyplot as plt 
import folium
import csv
import pandas as pd
import geopandas as gpd

In [540]:
 
overall_results = pd.read_csv("results.csv")
overall_results.head(10)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
5,6,18,6,3,8,13,6,6,6,3.0,57,\N,\N,50,14,1:29.639,212.974,11
6,7,18,7,5,14,17,7,7,7,2.0,55,\N,\N,22,12,1:29.534,213.224,5
7,8,18,8,6,1,15,8,8,8,1.0,53,\N,\N,20,4,1:27.903,217.180,5
8,9,18,9,2,4,2,\N,R,9,0.0,47,\N,\N,15,9,1:28.753,215.100,4
9,10,18,10,7,12,18,\N,R,10,0.0,43,\N,\N,23,13,1:29.558,213.166,3

In [541]:
overall_results['fastestLapTime']

0        1:27.452
1        1:27.739
2        1:28.090
3        1:28.603
4        1:27.418
           ...
25394    1:26.419
25395    1:29.293
25396    1:29.442
25397    1:30.647
25398    1:29.698
Name: fastestLapTime, Length: 25399, dtype: object

In [542]:
#the dataset might have NaN values since it has results from 50s and 60s where measurements were not as effective as today 
results.count()

resultId           25399
raceId             25399
driverId           25399
constructorId      25399
number             25399
grid               25399
position           25399
positionText       25399
positionOrder      25399
points             25399
laps               25399
time               25399
milliseconds       25399
fastestLap         25399
rank               25399
fastestLapTime     25399
fastestLapSpeed    25399
statusId           25399
dtype: int64

In [543]:
#check number of null values
overall_results.isnull().sum()

resultId           0
raceId             0
driverId           0
constructorId      0
number             0
grid               0
position           0
positionText       0
positionOrder      0
points             0
laps               0
time               0
milliseconds       0
fastestLap         0
rank               0
fastestLapTime     0
fastestLapSpeed    0
statusId           0
dtype: int64

In [544]:
#we then drop them if any exists
overall_results.dropna(inplace=True) 

#check again
overall_results.isnull().sum()

resultId           0
raceId             0
driverId           0
constructorId      0
number             0
grid               0
position           0
positionText       0
positionOrder      0
points             0
laps               0
time               0
milliseconds       0
fastestLap         0
rank               0
fastestLapTime     0
fastestLapSpeed    0
statusId           0
dtype: int64

In [545]:
overall_results['fastestLapTime']

0        1:27.452
1        1:27.739
2        1:28.090
3        1:28.603
4        1:27.418
           ...
25394    1:26.419
25395    1:29.293
25396    1:29.442
25397    1:30.647
25398    1:29.698
Name: fastestLapTime, Length: 25399, dtype: object

In [546]:
overall_results.head(25)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
5,6,18,6,3,8,13,6,6,6,3.0,57,\N,\N,50,14,1:29.639,212.974,11
6,7,18,7,5,14,17,7,7,7,2.0,55,\N,\N,22,12,1:29.534,213.224,5
7,8,18,8,6,1,15,8,8,8,1.0,53,\N,\N,20,4,1:27.903,217.180,5
8,9,18,9,2,4,2,\N,R,9,0.0,47,\N,\N,15,9,1:28.753,215.100,4
9,10,18,10,7,12,18,\N,R,10,0.0,43,\N,\N,23,13,1:29.558,213.166,3
10,11,18,11,8,18,19,\N,R,11,0.0,32,\N,\N,24,15,1:30.892,210.038,7
11,12,18,12,4,6,20,\N,R,12,0.0,30,\N,\N,20,16,1:31.384,208.907,8
12,13,18,13,6,2,4,\N,R,13,0.0,29,\N,\N,23,6,1:28.175,216.510,5
13,14,18,14,9,9,8,\N,R,14,0.0,25,\N,\N,21,11,1:29.502,213.300,4
14,15,18,15,7,11,6,\N,R,15,0.0,19,\N,\N,18,10,1:29.310,213.758,10
15,16,18,16,10,20,22,\N,R,16,0.0,8,\N,\N,8,17,1:32.021,207.461,9
16,17,18,17,9,10,14,\N,R,17,0.0,0,\N,\N,\N,\N,\N,\N,4
17,18,18,18,11,16,12,\N,R,18,0.0,0,\N,\N,\N,\N,\N,\N,4
18,19,18,19,8,19,21,\N,R,19,0.0,0,\N,\N,\N,\N,\N,\N,4
19,20,18,20,5,15,9,\N,R,20,0.0,0,\N,\N,\N,\N,\N,\N,4
20,21,18,21,10,21,16,\N,R,21,0.0,0,\N,\N,\N,\N,\N,\N,4
21,22,18,22,11,17,10,\N,D,22,0.0,58,\N,\N,44,8,1:28.736,215.141,2
22,23,19,8,6,1,2,1,1,1,10.0,56,1:31:18.555,5478555,37,2,1:35.405,209.158,1
23,24,19,9,2,4,4,2,2,2,8.0,56,+19.570,5498125,39,6,1:35.921,208.033,1
24,25,19,5,1,23,8,3,3,3,6.0,56,+38.450,5517005,19,7,1:35.922,208.031,1

In [547]:
#Eventually I want to merge the Drivers and their results

all_drivers = pd.read_csv("drivers.csv")

all_drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [548]:
#here comes the merging

merge_results = pd.merge(overall_results, all_drivers, how ="inner", on = "driverId")

merge_results.head(25)

,resultId,raceId,driverId,constructorId,number_x,grid,position,positionText,positionOrder,points,...,fastestLapSpeed,statusId,driverRef,number_y,code,forename,surname,dob,nationality,url
0,1,18,1,1,22,1,1,1,1,10.0,...,218.300,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,27,19,1,1,22,9,5,5,5,4.0,...,209.033,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
2,57,20,1,1,22,3,13,13,13,0.0,...,203.969,11,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
3,69,21,1,1,22,5,3,3,3,6.0,...,204.323,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
4,90,22,1,1,22,3,2,2,2,8.0,...,222.085,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
5,109,23,1,1,22,3,1,1,1,10.0,...,153.152,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
6,147,24,1,1,22,1,\N,R,19,0.0,...,202.559,4,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
7,158,25,1,1,22,13,10,10,10,0.0,...,205.022,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
8,169,26,1,1,22,4,1,1,1,10.0,...,199.398,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
9,189,27,1,1,22,1,1,1,1,10.0,...,216.552,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
10,213,28,1,1,22,1,5,5,5,4.0,...,193.533,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
11,230,29,1,1,22,2,2,2,2,8.0,...,197.285,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
12,251,30,1,1,22,1,3,3,3,6.0,...,233.175,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
13,275,31,1,1,22,15,7,7,7,2.0,...,232.440,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
14,291,32,1,1,22,2,3,3,3,6.0,...,171.969,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
15,320,33,1,1,22,1,12,12,12,0.0,...,206.470,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
16,329,34,1,1,22,1,1,1,1,10.0,...,203.722,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
17,353,35,1,1,22,4,5,5,5,4.0,...,209.177,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
18,371,36,1,1,2,4,3,3,3,6.0,...,221.083,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
19,392,37,1,1,2,4,2,2,2,8.0,...,206.355,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
20,414,38,1,1,2,2,2,2,2,8.0,...,206.674,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
21,436,39,1,1,2,4,2,2,2,8.0,...,202.205,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
22,458,40,1,1,2,2,2,2,2,8.0,...,159.528,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
23,479,41,1,1,2,1,1,1,1,10.0,...,205.239,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
24,501,42,1,1,2,1,1,1,1,10.0,...,206.101,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton

In [549]:
#specify collumns

merge_results = merge_results.drop(['url', 'points', 'position', 'laps', 'code', 'forename', 'code', 'number_y'], axis = 1)

merge_results

,resultId,raceId,driverId,constructorId,number_x,grid,positionText,positionOrder,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,driverRef,surname,dob,nationality
0,1,18,1,1,22,1,1,1,1:34:50.616,5690616,39,2,1:27.452,218.300,1,hamilton,Hamilton,1985-01-07,British
1,27,19,1,1,22,9,5,5,+46.548,5525103,53,3,1:35.462,209.033,1,hamilton,Hamilton,1985-01-07,British
2,57,20,1,1,22,3,13,13,\N,\N,25,19,1:35.520,203.969,11,hamilton,Hamilton,1985-01-07,British
3,69,21,1,1,22,5,3,3,+4.187,5903238,20,3,1:22.017,204.323,1,hamilton,Hamilton,1985-01-07,British
4,90,22,1,1,22,3,2,2,+3.779,5213230,31,2,1:26.529,222.085,1,hamilton,Hamilton,1985-01-07,British
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25394,25302,1069,853,210,9,17,17,17,\N,\N,42,20,1:42.886,192.900,12,mazepin,Mazepin,1999-03-02,Russian
25395,25323,1070,853,210,9,15,18,18,\N,\N,61,15,1:21.402,190.344,13,mazepin,Mazepin,1999-03-02,Russian
25396,25342,1071,853,210,9,19,17,17,\N,\N,36,19,1:14.954,206.958,12,mazepin,Mazepin,1999-03-02,Russian
25397,25363,1051,853,210,9,20,18,18,\N,\N,55,16,1:27.340,221.754,12,mazepin,Mazepin,1999-03-02,Russian
25398,25383,1072,853,210,9,20,R,18,\N,\N,7,20,1:37.043,229.036,4,mazepin,Mazepin,1999-03-02,Russian

In [550]:
#read and drop columns of other relevant files 




#races

races = pd.read_csv('races.csv')
races = races.drop(['url', 'round','time'], axis =1 )

races.tail(50)

      raceId  year  circuitId                       name        date
1030    1043  2020         21  Emilia Romagna Grand Prix  2020-11-01
1031    1044  2020          5         Turkish Grand Prix  2020-11-15
1032    1045  2020          3         Bahrain Grand Prix  2020-11-29
1033    1046  2020          3          Sakhir Grand Prix  2020-12-06
1034    1047  2020         24       Abu Dhabi Grand Prix  2020-12-13
1035    1053  2021         21  Emilia Romagna Grand Prix  2021-04-18
1036    1074  2022          3         Bahrain Grand Prix  2022-03-20
1037    1052  2021          3         Bahrain Grand Prix  2021-03-28
1038    1051  2021         78           Qatar Grand Prix  2021-11-21
1039    1054  2021         75      Portuguese Grand Prix  2021-05-02
1040    1055  2021          4         Spanish Grand Prix  2021-05-09
1041    1056  2021          6          Monaco Grand Prix  2021-05-23
1042    1057  2021         73      Azerbaijan Grand Prix  2021-06-06
1043    1058  2021         70         Styrian Grand Prix  2021-06-27
1044    1059  2021         34          French Grand Prix  2021-06-20
1045    1060  2021         70        Austrian Grand Prix  2021-07-04
1046    1061  2021          9         British Grand Prix  2021-07-18
1047    1062  2021         11       Hungarian Grand Prix  2021-08-01
1048    1063  2021         13         Belgian Grand Prix  2021-08-29
1049    1064  2021         39           Dutch Grand Prix  2021-09-05
1050    1065  2021         14         Italian Grand Prix  2021-09-12
1051    1066  2021         71         Russian Grand Prix  2021-09-26
1052    1067  2021          5         Turkish Grand Prix  2021-10-10
1053    1069  2021         69   United States Grand Prix  2021-10-24
1054    1070  2021         32     Mexico City Grand Prix  2021-11-07
1055    1071  2021         18       São Paulo Grand Prix  2021-11-14
1056    1072  2021         77   Saudi Arabian Grand Prix  2021-12-05
1057    1073  2021         24       Abu Dhabi Grand Prix  2021-12-12
1058    1075  2022         77   Saudi Arabian Grand Prix  2022-03-27
1059    1076  2022          1      Australian Grand Prix  2022-04-10
1060    1077  2022         21  Emilia Romagna Grand Prix  2022-04-24
1061    1078  2022         79           Miami Grand Prix  2022-05-08
1062    1079  2022          4         Spanish Grand Prix  2022-05-22
1063    1080  2022          6          Monaco Grand Prix  2022-05-29
1064    1081  2022         73      Azerbaijan Grand Prix  2022-06-12
1065    1082  2022          7        Canadian Grand Prix  2022-06-19
1066    1083  2022          9         British Grand Prix  2022-07-03
1067    1084  2022         70        Austrian Grand Prix  2022-07-12
1068    1085  2022         34          French Grand Prix  2022-07-24
1069    1086  2022         11       Hungarian Grand Prix  2022-07-31
1070    1087  2022         13         Belgian Grand Prix  2022-08-28
1071    1088  2022         39           Dutch Grand Prix  2022-09-04
1072    1089  2022         14         Italian Grand Prix  2022-09-11
1073    1090  2022         71         Russian Grand Prix  2022-09-25
1074    1091  2022         15       Singapore Grand Prix  2022-10-02
1075    1092  2022         22        Japanese Grand Prix  2022-10-09
1076    1093  2022         69   United States Grand Prix  2022-10-23
1077    1094  2022         32     Mexico City Grand Prix  2022-10-30
1078    1095  2022         18       São Paulo Grand Prix  2022-11-13
1079    1096  2022         24       Abu Dhabi Grand Prix  2022-11-20

In [551]:
#2021 races

races_2021 = races[races["year"] == 2021 ]

races_2021

      raceId  year  circuitId                       name        date
1035    1053  2021         21  Emilia Romagna Grand Prix  2021-04-18
1037    1052  2021          3         Bahrain Grand Prix  2021-03-28
1038    1051  2021         78           Qatar Grand Prix  2021-11-21
1039    1054  2021         75      Portuguese Grand Prix  2021-05-02
1040    1055  2021          4         Spanish Grand Prix  2021-05-09
1041    1056  2021          6          Monaco Grand Prix  2021-05-23
1042    1057  2021         73      Azerbaijan Grand Prix  2021-06-06
1043    1058  2021         70         Styrian Grand Prix  2021-06-27
1044    1059  2021         34          French Grand Prix  2021-06-20
1045    1060  2021         70        Austrian Grand Prix  2021-07-04
1046    1061  2021          9         British Grand Prix  2021-07-18
1047    1062  2021         11       Hungarian Grand Prix  2021-08-01
1048    1063  2021         13         Belgian Grand Prix  2021-08-29
1049    1064  2021         39           Dutch Grand Prix  2021-09-05
1050    1065  2021         14         Italian Grand Prix  2021-09-12
1051    1066  2021         71         Russian Grand Prix  2021-09-26
1052    1067  2021          5         Turkish Grand Prix  2021-10-10
1053    1069  2021         69   United States Grand Prix  2021-10-24
1054    1070  2021         32     Mexico City Grand Prix  2021-11-07
1055    1071  2021         18       São Paulo Grand Prix  2021-11-14
1056    1072  2021         77   Saudi Arabian Grand Prix  2021-12-05
1057    1073  2021         24       Abu Dhabi Grand Prix  2021-12-12

In [552]:
#maps of the 2021 races

import matplotlib.pyplot as plt 
import folium

In [553]:
circuits = pd.read_csv('circuits.csv')

circuits

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park
...,...,...,...,...,...,...,...,...,...
74,75,portimao,Autódromo Internacional do Algarve,Portimão,Portugal,37.22700,-8.62670,108,http://en.wikipedia.org/wiki/Algarve_Internati...
75,76,mugello,Autodromo Internazionale del Mugello,Mugello,Italy,43.99750,11.37190,255,http://en.wikipedia.org/wiki/Mugello_Circuit
76,77,jeddah,Jeddah Street Circuit,Jeddah,Saudi Arabia,21.54330,39.17280,15,http://en.wikipedia.org/wiki/Jeddah_Street_Cir...
77,78,losail,Losail International Circuit,Al Daayen,Qatar,25.49000,51.45420,\N,http://en.wikipedia.org/wiki/Losail_Internatio...
78,79,miami,Miami International Autodrome,Miami,United States,25.95810,-80.23890,\N,https://en.wikipedia.org/wiki/Miami_Internatio...

In [554]:
circuits = pd.read_csv('circuits.csv')

circuits_2021 = circuits.drop(['circuitRef', 'alt', 'url'], axis = 1)





circuits_2021

,circuitId,name,location,country,lat,lng
0,1,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800
1,2,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800
2,3,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060
3,4,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111
4,5,Istanbul Park,Istanbul,Turkey,40.95170,29.40500
...,...,...,...,...,...,...
74,75,Autódromo Internacional do Algarve,Portimão,Portugal,37.22700,-8.62670
75,76,Autodromo Internazionale del Mugello,Mugello,Italy,43.99750,11.37190
76,77,Jeddah Street Circuit,Jeddah,Saudi Arabia,21.54330,39.17280
77,78,Losail International Circuit,Al Daayen,Qatar,25.49000,51.45420
78,79,Miami International Autodrome,Miami,United States,25.95810,-80.23890

In [555]:
circuits_2021 = pd.merge(circuits_2021, races_2021, how = "inner", on='circuitId')
circuits_2021

,circuitId,name_x,location,country,lat,lng,raceId,year,name_y,date
0,3,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.51060,1052,2021,Bahrain Grand Prix,2021-03-28
1,4,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.5700,2.26111,1055,2021,Spanish Grand Prix,2021-05-09
2,5,Istanbul Park,Istanbul,Turkey,40.9517,29.40500,1067,2021,Turkish Grand Prix,2021-10-10
3,6,Circuit de Monaco,Monte-Carlo,Monaco,43.7347,7.42056,1056,2021,Monaco Grand Prix,2021-05-23
4,9,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,1061,2021,British Grand Prix,2021-07-18
5,11,Hungaroring,Budapest,Hungary,47.5789,19.24860,1062,2021,Hungarian Grand Prix,2021-08-01
6,13,Circuit de Spa-Francorchamps,Spa,Belgium,50.4372,5.97139,1063,2021,Belgian Grand Prix,2021-08-29
7,14,Autodromo Nazionale di Monza,Monza,Italy,45.6156,9.28111,1065,2021,Italian Grand Prix,2021-09-12
8,18,Autódromo José Carlos Pace,São Paulo,Brazil,-23.7036,-46.69970,1071,2021,São Paulo Grand Prix,2021-11-14
9,21,Autodromo Enzo e Dino Ferrari,Imola,Italy,44.3439,11.71670,1053,2021,Emilia Romagna Grand Prix,2021-04-18
10,24,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.60310,1073,2021,Abu Dhabi Grand Prix,2021-12-12
11,32,Autódromo Hermanos Rodríguez,Mexico City,Mexico,19.4042,-99.09070,1070,2021,Mexico City Grand Prix,2021-11-07
12,34,Circuit Paul Ricard,Le Castellet,France,43.2506,5.79167,1059,2021,French Grand Prix,2021-06-20
13,39,Circuit Park Zandvoort,Zandvoort,Netherlands,52.3888,4.54092,1064,2021,Dutch Grand Prix,2021-09-05
14,69,Circuit of the Americas,Austin,USA,30.1328,-97.64110,1069,2021,United States Grand Prix,2021-10-24
15,70,Red Bull Ring,Spielberg,Austria,47.2197,14.76470,1058,2021,Styrian Grand Prix,2021-06-27
16,70,Red Bull Ring,Spielberg,Austria,47.2197,14.76470,1060,2021,Austrian Grand Prix,2021-07-04
17,71,Sochi Autodrom,Sochi,Russia,43.4057,39.95780,1066,2021,Russian Grand Prix,2021-09-26
18,73,Baku City Circuit,Baku,Azerbaijan,40.3725,49.85330,1057,2021,Azerbaijan Grand Prix,2021-06-06
19,75,Autódromo Internacional do Algarve,Portimão,Portugal,37.2270,-8.62670,1054,2021,Portuguese Grand Prix,2021-05-02
20,77,Jeddah Street Circuit,Jeddah,Saudi Arabia,21.5433,39.17280,1072,2021,Saudi Arabian Grand Prix,2021-12-05
21,78,Losail International Circuit,Al Daayen,Qatar,25.4900,51.45420,1051,2021,Qatar Grand Prix,2021-11-21

In [556]:
#maps of the circuits

#my_map = folium.Map(
        #location = [-37.84970, 144.96800], zoom_start = 2)
#my_map

#circuit = circuits.loc[0]

#for _, circuits in circuits_2021.iterrows(): 
    #folium.Marker(
      #      location = [circuits_2021['lat'], circuits_2021['lng']], 
       #     popup = circuits_2021['name_x'],
       #     tooltip = circuits_2021['name_x']
   # ).add_to(my_map)

#my_map

In [557]:
races_status = pd.read_csv("status.csv")

races_status.head()

   statusId        status
0         1      Finished
1         2  Disqualified
2         3      Accident
3         4     Collision
4         5        Engine

In [558]:
#merge and race status

merge_2 = pd.merge(merge_results, races_status, how = "inner", on='statusId')

merge_2.head()

,resultId,raceId,driverId,constructorId,number_x,grid,positionText,positionOrder,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,driverRef,surname,dob,nationality,status
0,1,18,1,1,22,1,1,1,1:34:50.616,5690616,39,2,1:27.452,218.300,1,hamilton,Hamilton,1985-01-07,British,Finished
1,27,19,1,1,22,9,5,5,+46.548,5525103,53,3,1:35.462,209.033,1,hamilton,Hamilton,1985-01-07,British,Finished
2,69,21,1,1,22,5,3,3,+4.187,5903238,20,3,1:22.017,204.323,1,hamilton,Hamilton,1985-01-07,British,Finished
3,90,22,1,1,22,3,2,2,+3.779,5213230,31,2,1:26.529,222.085,1,hamilton,Hamilton,1985-01-07,British,Finished
4,109,23,1,1,22,3,1,1,2:00:42.742,7242742,71,6,1:18.510,153.152,1,hamilton,Hamilton,1985-01-07,British,Finished

In [559]:
#refining and dropping columns 

merge_2_refined = merge_2.drop(['driverId', 'statusId', 'driverRef', 'nationality', 'dob'], axis = 1)

merge_2_refined.head()

,resultId,raceId,constructorId,number_x,grid,positionText,positionOrder,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,surname,status
0,1,18,1,22,1,1,1,1:34:50.616,5690616,39,2,1:27.452,218.300,Hamilton,Finished
1,27,19,1,22,9,5,5,+46.548,5525103,53,3,1:35.462,209.033,Hamilton,Finished
2,69,21,1,22,5,3,3,+4.187,5903238,20,3,1:22.017,204.323,Hamilton,Finished
3,90,22,1,22,3,2,2,+3.779,5213230,31,2,1:26.529,222.085,Hamilton,Finished
4,109,23,1,22,3,1,1,2:00:42.742,7242742,71,6,1:18.510,153.152,Hamilton,Finished

In [560]:
#merging races and data

refined_data = pd.merge(merge_2_refined, races, how = "inner", on='raceId')

refined_data.head(5)

,resultId,raceId,constructorId,number_x,grid,positionText,positionOrder,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,surname,status,year,circuitId,name,date
0,1,18,1,22,1,1,1,1:34:50.616,5690616,39,2,1:27.452,218.300,Hamilton,Finished,2008,1,Australian Grand Prix,2008-03-16
1,2,18,2,3,5,2,2,+5.478,5696094,41,3,1:27.739,217.586,Heidfeld,Finished,2008,1,Australian Grand Prix,2008-03-16
2,3,18,3,7,7,3,3,+8.163,5698779,41,5,1:28.090,216.719,Rosberg,Finished,2008,1,Australian Grand Prix,2008-03-16
3,4,18,4,5,11,4,4,+17.181,5707797,58,7,1:28.603,215.464,Alonso,Finished,2008,1,Australian Grand Prix,2008-03-16
4,5,18,1,23,3,5,5,+18.014,5708630,43,1,1:27.418,218.385,Kovalainen,Finished,2008,1,Australian Grand Prix,2008-03-16